---

resource_types:
- name: git-branch-heads
  type: docker-image
  source: {repository: vito/git-branch-heads-resource}

resources:
  - name: hello-world-python-repo
    type: git-branch-heads
    source:
      uri: git@github.com:picklecillo/python_concourse_cloudrun.git
      branches: [master]
      private_key: ((ssh_private_key))

jobs:
  - name: test
    public: true
    plan:
      - get: hello-world-python-repo
      - task: setup-dev-dependencies
        config:
          inputs:
            - name: hello-world-python-repo
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: 3.6-alpine
          run:
            dir: hello-world-python-repo
            path: /bin/sh
            args:
              - ./scripts.sh
              - init_workspace
              - dev
          outputs:
            - name: hello-world-python-repo
      - task: lint
        config:
          inputs:
            - name: hello-world-python-repo
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: 3.6-alpine
          run:
            dir: hello-world-python-repo
            path: /bin/sh
            args:
              - -c
              - mkdir -p /root/.local/lib/python3.6/site-packages
              - cp -r dependencies/* /root/.local/lib/python3.6/site-packages
              - sh scripts.sh lint
      - task: all_tests
        config:
          inputs:
            - name: hello-world-python-repo
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: 3.6-alpine
          run:
            dir: hello-world-python-repo
            path: /bin/sh
            args:
              - -c
              - mkdir -p /root/.local/lib/python3.6/site-packages && cp -r dependencies/* /root/.local/lib/python3.6/site-packages && sh scripts.sh all_tests
